// frontend/src/App.jsx
import React from 'react';

import {
  Layout, Menu, Breadcrumb, Icon,
} from 'antd';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link,
} from 'react-router-dom';

import Register from './components/Register'
import './App.css';

const { SubMenu } = Menu;

const { Content, Sider } = Layout;

const App = () => (
  <Layout>
    <Router>
      <Sider width={200} style={{ background: '#fff' }}>
        <Menu
          mode="inline"
          defaultOpenKeys={['projects_menu']}
          style={{ height: '100%', borderRight: 0 }}
        >
          <SubMenu
            key="profile_menu"
            title={(
              <span>
                <Icon type="user" />
                Profile
              </span>
              )}
          >
            <Menu.Item key="profile_link">
              <Link to="/profile">Edit profile</Link>
            </Menu.Item>
            <Menu.Item key="logout_button">Log out</Menu.Item>
          </SubMenu>
          <SubMenu
            key="projects_menu"
            title={(
              <span>
                <Icon type="laptop" />
                Projects
              </span>
              )}
          >
            <Menu.Item key="projectId">
              <Link to="/projects/project1">project 1</Link>
            </Menu.Item>
          </SubMenu>
        </Menu>
      </Sider>
      <Layout style={{ padding: '0 24px 24px' }}>
        <Breadcrumb style={{ margin: '16px 0' }}>
          <Breadcrumb.Item>
            <Link to="/">Home</Link>
          </Breadcrumb.Item>
          <Breadcrumb.Item>List</Breadcrumb.Item>
          <Breadcrumb.Item>App</Breadcrumb.Item>
        </Breadcrumb>
        <Content
          style={{
            background: '#fff',
            padding: 24,
            margin: 0,
            minHeight: 280,
          }}
        >
          <Switch>
            <Route path="/profile">
             add profile component here
            </Route>
            <Route path="/projects/:projectId">
             add project component here
            </Route>
            <Route path="/register">
              <Register />
            </Route>
            <Route path="/">
             add home component here
            </Route>
          </Switch>
        </Content>
      </Layout>
    </Router>
  </Layout>
);

export default App;

// frontend/src/App.vue
<template>
  <a-layout id="app" style="min-height: 100vh;">
    <a-layout-sider collapsible v-model="collapsed">
      <div class="logo" />
      <a-menu :default-selected-keys="['1']" mode="inline" theme="dark">
        <a-sub-menu key="sub2">
          <span slot="title">
            <a-icon type="project" />
            <span>Projects</span>
          </span>
          <a-menu-item key="6">Team 1</a-menu-item>
          <a-menu-item key="8">Team 2</a-menu-item>
        </a-sub-menu>
        <a-menu-item key="9">
          <a-icon type="stock" />
          <span>Analytics</span>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header style="background: #fff; padding: 0; margin-bottom: 25px;">
        <a-button icon="plus">New Project</a-button>
      </a-layout-header>
      <a-layout-content style="margin: 0 16px;">
        <Boards />
      </a-layout-content>
    </a-layout>
  </a-layout>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
import Boards from './components/Boards'

export default {
  name: "App",
  components: {
    Boards
  },
  data() {
    return {
      collapsed: false,
    };
  },
};
</script>

<style>
#app .logo {
  height: 32px;
  background: rgba(255, 255, 255, 0.2);
  margin: 16px;
}
</style>
